[build]
  command = "npm run build"
  functions = ".netlify/functions"
  publish = ".nuxt/dist/client"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nuxt"
  status = 200